# Generated by Django 5.0.3 on 2024-03-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='itemName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='listPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
