# Generated by Django 5.0.3 on 2024-03-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_react_employee_react_category_react_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='stock',
        ),
        migrations.AddField(
            model_name='react',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
