# Generated by Django 5.0.3 on 2024-03-12 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_react_stock_react_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddField(
            model_name='react',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
