# Generated by Django 5.0.3 on 2024-03-13 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_inventoryitem_react_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
